name: Deploy API to Azure
on:
  push:
    branches:
      - main  # or your default branch name
  workflow_dispatch:  # Allows manual trigger

env:
  AZURE_WEBAPP_NAME: brianle-budget-tracker-api    # Replace with your app name
  AZURE_WEBAPP_PACKAGE_PATH: './budget-tracking-api/BudgetTracking.API'  # Path to your API project
  DB_PROJECT_PATH: './budget-tracking-api/BudgetTracking.Db'
  DOTNET_VERSION: '9.0.x'             # Your project uses .NET 9
  CONNECTION_STRING: ${{ secrets.NEON_DB_CONNECTION_STRING }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
    
    - name: Restore dependencies
      run: dotnet restore ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/BudgetTracking.API.csproj
    
    - name: Build
      run: dotnet build ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/BudgetTracking.API.csproj --configuration Release --no-restore
    
    - name: Test
      run: dotnet test ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/BudgetTracking.API.csproj --no-restore --verbosity normal
    
    - name: Install EF Core CLI
      run: dotnet tool install --global dotnet-ef
      
    - name: Apply Database Migrations
      run: dotnet ef database update --project ${{env.DB_PROJECT_PATH}} --startup-project ${{env.AZURE_WEBAPP_PACKAGE_PATH}} --connection "${{ env.CONNECTION_STRING }}"
    
    - name: Publish
      run: dotnet publish ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/BudgetTracking.API.csproj -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/publish
    
    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ${{env.AZURE_WEBAPP_PACKAGE_PATH}}/publish
